//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVQuickManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVQuickManager.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is now {1}.
        /// </summary>
        internal static string Balloon_Message {
            get {
                return ResourceManager.GetString("Balloon_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  but is in a critical state.
        /// </summary>
        internal static string Balloon_MessageExtensionCritical {
            get {
                return ResourceManager.GetString("Balloon_MessageExtensionCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine {0}.
        /// </summary>
        internal static string Balloon_Title {
            get {
                return ResourceManager.GetString("Balloon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to change the state of &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ChangeState_InstructionText {
            get {
                return ResourceManager.GetString("Error_ChangeState_InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to change the state of one or more virtual machines..
        /// </summary>
        internal static string Error_ChangeState_InstructionTextMultiple {
            get {
                return ResourceManager.GetString("Error_ChangeState_InstructionTextMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} machines failed to change state..
        /// </summary>
        internal static string Error_ChangeState_TextMultiple {
            get {
                return ResourceManager.GetString("Error_ChangeState_TextMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires administrative rights..
        /// </summary>
        internal static string Error_RequiresAdminDesktop_InstructionText {
            get {
                return ResourceManager.GetString("Error_RequiresAdminDesktop_InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires administrative rights when run in standalone mode. To run without requiring administrative rights you can install the application as a Windows Service..
        /// </summary>
        internal static string Error_RequiresAdminDesktop_Text {
            get {
                return ResourceManager.GetString("Error_RequiresAdminDesktop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be run as a user account that has administrative rights on this computer..
        /// </summary>
        internal static string Error_RequiresAdminService {
            get {
                return ResourceManager.GetString("Error_RequiresAdminService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative rights are required to install {0} as a Windows Service..
        /// </summary>
        internal static string Error_RequiresAdminToInstall_InstructionText {
            get {
                return ResourceManager.GetString("Error_RequiresAdminToInstall_InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires administrative rights in order to install as a Windows Service. Please run the command line again from an elevated command prompt..
        /// </summary>
        internal static string Error_RequiresAdminToInstall_Text {
            get {
                return ResourceManager.GetString("Error_RequiresAdminToInstall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service failed to start with the following error: {0}.
        /// </summary>
        internal static string Error_ServiceFailedToStart {
            get {
                return ResourceManager.GetString("Error_ServiceFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported on this Operating System..
        /// </summary>
        internal static string Error_Unsupported_InstructionText {
            get {
                return ResourceManager.GetString("Error_Unsupported_InstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is only supported on Windows 8 or later and Windows Server 2008 or later..
        /// </summary>
        internal static string Error_Unsupported_Text {
            get {
                return ResourceManager.GetString("Error_Unsupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Virtual Machines.
        /// </summary>
        internal static string Menu_AllVirtualMachines {
            get {
                return ResourceManager.GetString("Menu_AllVirtualMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        internal static string Menu_Connect {
            get {
                return ResourceManager.GetString("Menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect and Resume....
        /// </summary>
        internal static string Menu_ConnectAndResume {
            get {
                return ResourceManager.GetString("Menu_ConnectAndResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect and Start....
        /// </summary>
        internal static string Menu_ConnectAndStart {
            get {
                return ResourceManager.GetString("Menu_ConnectAndStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V Manager.
        /// </summary>
        internal static string Menu_HyperVManager {
            get {
                return ResourceManager.GetString("Menu_HyperVManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Menu_Pause {
            get {
                return ResourceManager.GetString("Menu_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Menu_Resume {
            get {
                return ResourceManager.GetString("Menu_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down....
        /// </summary>
        internal static string Menu_ShutDown {
            get {
                return ResourceManager.GetString("Menu_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Menu_Start {
            get {
                return ResourceManager.GetString("Menu_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off....
        /// </summary>
        internal static string Menu_TurnOff {
            get {
                return ResourceManager.GetString("Menu_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides support for running {0}..
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string State_Critical {
            get {
                return ResourceManager.GetString("State_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string State_Paused {
            get {
                return ResourceManager.GetString("State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing.
        /// </summary>
        internal static string State_Pausing {
            get {
                return ResourceManager.GetString("State_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting.
        /// </summary>
        internal static string State_Resetting {
            get {
                return ResourceManager.GetString("State_Resetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming.
        /// </summary>
        internal static string State_Resuming {
            get {
                return ResourceManager.GetString("State_Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string State_Saved {
            get {
                return ResourceManager.GetString("State_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string State_Saving {
            get {
                return ResourceManager.GetString("State_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string State_Starting {
            get {
                return ResourceManager.GetString("State_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string State_Stopped {
            get {
                return ResourceManager.GetString("State_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string State_Stopping {
            get {
                return ResourceManager.GetString("State_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string State_Unknown {
            get {
                return ResourceManager.GetString("State_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string StateChangeResponse_AccessDenied {
            get {
                return ResourceManager.GetString("StateChangeResponse_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully.
        /// </summary>
        internal static string StateChangeResponse_CompletedwithNoError {
            get {
                return ResourceManager.GetString("StateChangeResponse_CompletedwithNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed.
        /// </summary>
        internal static string StateChangeResponse_Failed {
            get {
                return ResourceManager.GetString("StateChangeResponse_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect data type was specified.
        /// </summary>
        internal static string StateChangeResponse_IncorrectDataType {
            get {
                return ResourceManager.GetString("StateChangeResponse_IncorrectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid parameter was specified.
        /// </summary>
        internal static string StateChangeResponse_InvalidParameter {
            get {
                return ResourceManager.GetString("StateChangeResponse_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Virtual Machine is in an invalid state for this operation.
        /// </summary>
        internal static string StateChangeResponse_InvalidStateForThisOperation {
            get {
                return ResourceManager.GetString("StateChangeResponse_InvalidStateForThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameters Checked - Transition Started.
        /// </summary>
        internal static string StateChangeResponse_MethodParametersCheckedTransitionStarted {
            get {
                return ResourceManager.GetString("StateChangeResponse_MethodParametersCheckedTransitionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not supported.
        /// </summary>
        internal static string StateChangeResponse_NotSupported {
            get {
                return ResourceManager.GetString("StateChangeResponse_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string StateChangeResponse_OutOfMemory {
            get {
                return ResourceManager.GetString("StateChangeResponse_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine status is unknown.
        /// </summary>
        internal static string StateChangeResponse_StatusIsUnknown {
            get {
                return ResourceManager.GetString("StateChangeResponse_StatusIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is in use.
        /// </summary>
        internal static string StateChangeResponse_SystemIsInUse {
            get {
                return ResourceManager.GetString("StateChangeResponse_SystemIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is not available.
        /// </summary>
        internal static string StateChangeResponse_SystemIsNotAvailable {
            get {
                return ResourceManager.GetString("StateChangeResponse_SystemIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occured.
        /// </summary>
        internal static string StateChangeResponse_Timeout {
            get {
                return ResourceManager.GetString("StateChangeResponse_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        internal static string StateChangeResponse_UnknownError {
            get {
                return ResourceManager.GetString("StateChangeResponse_UnknownError", resourceCulture);
            }
        }
    }
}
